version: '3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
            db:
                condition: service_healthy
    environment:
      pass: root
